### ISSUE TITLE
"/" vs "\" to avoid syntax error

### ISSUE THREAD

**Issue by madisonsorah** [learn-co-curriculum/phase-3-control-flow-conditional-statements#1]
### Canvas Link

https://learning.flatironschool.com/courses/4551/assignments/160844?confetti=true&submitted=0

### Concern

In the README, it states:

Write a method #calculator that takes three arguments: an operation and two numbers. If the operation is one of the following: +, -, *, or \, return the value of calling the operation on the two numbers. Otherwise, output a message saying "Invalid operation!" and return nil.

### Suggested Changes

Adding \ to the code, as asked above, returns a syntax error and **should be corrected to /** for clarity.

**Comment by lizbur10** [comment]
Thanks for flagging this @madisonsorah ! It has been fixed 💙
