### ISSUE TITLE
Python curriculum may have been published too soon

### ISSUE THREAD

**Issue by foreverluiscastro** [learn-co-curriculum/phase-3-control-flow-conditional-statements#4]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172599?module_item_id=376618

### Concern

The assignment on canvas reflect the ruby curriculum but if you click fork or the octocat icon the github repository reflects a python based curriculum. Just wanted to flag this because I don't believe student are suppose to have access to that yet.

### Suggested Changes

create a separate branch for the working python course so once that time comes you can merge the the branches.

**Comment by professor-ben** [comment]
Hi Luis,

So sorry for the conflict here! The Python changes have been moved back into the correct repo now, so you shouldn't see any issues at this point. Please continue to let us know if you see any issues.

Thanks,
Ben
